export const environment = {
  production: true,
  envName: 'Production',

  API_AUTHENTICATE: 'https://api-pub-authenticate.prd.idealeware.com.br',
  API_BANNER: 'https://api-pub-banner.prd.idealeware.com.br',
  API_BRANCH: 'https://api-pub-branch.prd.idealeware.com.br',
  API_BRAND: 'https://api-pub-brand.prd.idealeware.com.br',
  API_BUDGET: 'https://api-pub-budget.prd.idealeware.com.br',
  API_CART: 'https://api-pub-cart.prd.idealeware.com.br',
  API_CARTSHOWCASE: 'https://api-pub-cartshowcase.prd.idealeware.com.br',
  API_CATEGORY: 'https://api-pub-category.prd.idealeware.com.br',
  API_CONTACT: 'https://api-pub-contact.prd.idealeware.com.br',
  API_COUPON: 'https://api-pub-coupon.prd.idealeware.com.br',
  API_CUSTOMER: 'https://api-pub-customer.prd.idealeware.com.br',
  API_CUSTOMPAINT: 'https://api-pub-custompaint.prd.idealeware.com.br',
  API_DNEADDRESS: 'https://api-pub-dneaddress.prd.idealeware.com.br',
  API_GOOGLE: 'https://api-pub-google.prd.idealeware.com.br',
  API_GROUP: 'https://api-pub-group.prd.idealeware.com.br',
  API_INSTITUTIONAL: 'https://api-pub-institutional.prd.idealeware.com.br',
  API_INTELIPOST: 'https://api-pub-intelipost.prd.idealeware.com.br',
  API_ORDER: 'https://api-pub-order.prd.idealeware.com.br',
  API_ORDERVALIDATION: 'https://api-pub-ordervalidation.prd.idealeware.com.br',
  API_PAYMENTS: 'https://api-pub-payments.prd.idealeware.com.br',
  API_POPUP: 'https://api-pub-popup.prd.idealeware.com.br',
  API_PRODUCT: 'https://api-pub-product.prd.idealeware.com.br',
  API_PRODUCTAWAITED: 'https://api-pub-productsawaited.prd.idealeware.com.br',
  API_PRODUCTRATING: 'https://api-pub-productrating.prd.idealeware.com.br',
  API_REDIRECT301: 'https://api-pub-redirect301.prd.idealeware.com.br',
  API_RELATEDPRODUCTS: 'https://api-pub-relatedproducts.prd.idealeware.com.br',
  API_SEARCH: 'https://api-pub-search.prd.idealeware.com.br',
  API_SERVICE: 'https://api-pub-service.prd.idealeware.com.br',
  API_SHOWCASE: 'https://api-pub-showcase.prd.idealeware.com.br',
  API_STORE: 'https://api-pub-store.prd.idealeware.com.br',
  API_STORE_INFO: 'https://api-pub-storeinfo.prd.idealeware.com.br',
  API_FIPE: 'https://fipeapi.appspot.com/api/1/carros',
  SELF_COLOR_PALETA: '/assets/services'
};
